'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * ExaVault API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * See our API reference documentation at https://www.exavault.com/developer/api-docs/
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 2.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Contact: support@exavault.com
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _FormEntryField = require('./FormEntryField');

var _FormEntryField2 = _interopRequireDefault(_FormEntryField);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The FormEntryAttributes model module.
* @module model/FormEntryAttributes
* @version 2.2.1
*/
var FormEntryAttributes = function () {
    /**
    * Constructs a new <code>FormEntryAttributes</code>.
    * @alias module:model/FormEntryAttributes
    * @class
    */

    function FormEntryAttributes() {
        _classCallCheck(this, FormEntryAttributes);

        this['fields'] = undefined;
        this['paths'] = undefined;
        this['status'] = undefined;
        this['created'] = undefined;
        this['modified'] = undefined;
    }

    /**
    * Constructs a <code>FormEntryAttributes</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/FormEntryAttributes} obj Optional instance to populate.
    * @return {module:model/FormEntryAttributes} The populated <code>FormEntryAttributes</code> instance.
    */


    _createClass(FormEntryAttributes, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new FormEntryAttributes();

                if (data.hasOwnProperty('fields')) {
                    obj['fields'] = _ApiClient2.default.convertToType(data['fields'], [_FormEntryField2.default]);
                }
                if (data.hasOwnProperty('paths')) {
                    obj['paths'] = _ApiClient2.default.convertToType(data['paths'], ['String']);
                }
                if (data.hasOwnProperty('status')) {
                    obj['status'] = _ApiClient2.default.convertToType(data['status'], 'String');
                }
                if (data.hasOwnProperty('created')) {
                    obj['created'] = _ApiClient2.default.convertToType(data['created'], 'Date');
                }
                if (data.hasOwnProperty('modified')) {
                    obj['modified'] = _ApiClient2.default.convertToType(data['modified'], 'Date');
                }
            }
            return obj;
        }

        /**
        * @member {Array.<module:model/FormEntryField>} fields
        */

        /**
        * Full paths to files associated with the form submission
        * @member {Array.<String>} paths
        */

        /**
        * Form entry status
        * @member {module:model/FormEntryAttributes.StatusEnum} status
        */

        /**
        * Timestamp of the submission
        * @member {Date} created
        */

        /**
        * Timestamp of the field modified date
        * @member {Date} modified
        */


        /**
        * Allowed values for the <code>status</code> property.
        * @enum {String}
        * @readonly
        */

    }]);

    return FormEntryAttributes;
}();

FormEntryAttributes.StatusEnum = {
    /**
     * value: "pending"
     * @const
     */
    "pending": "pending",
    /**
     * value: "completed"
     * @const
     */
    "completed": "completed" };
exports.default = FormEntryAttributes;