'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * ExaVault API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * See our API reference documentation at https://www.exavault.com/developer/api-docs/
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 2.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Contact: support@exavault.com
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The FormFieldSettings model module.
* @module model/FormFieldSettings
* @version 2.2.3
*/
var FormFieldSettings = function () {
    /**
    * Constructs a new <code>FormFieldSettings</code>.
    * Advanced field settings
    * @alias module:model/FormFieldSettings
    * @class
    */

    function FormFieldSettings() {
        _classCallCheck(this, FormFieldSettings);

        this['description'] = undefined;
        this['width'] = undefined;
        this['isRequired'] = undefined;
        this['useAsFolderName'] = undefined;
        this['senderEmail'] = undefined;
    }

    /**
    * Constructs a <code>FormFieldSettings</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/FormFieldSettings} obj Optional instance to populate.
    * @return {module:model/FormFieldSettings} The populated <code>FormFieldSettings</code> instance.
    */


    _createClass(FormFieldSettings, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new FormFieldSettings();

                if (data.hasOwnProperty('description')) {
                    obj['description'] = _ApiClient2.default.convertToType(data['description'], 'String');
                }
                if (data.hasOwnProperty('width')) {
                    obj['width'] = _ApiClient2.default.convertToType(data['width'], 'Number');
                }
                if (data.hasOwnProperty('isRequired')) {
                    obj['isRequired'] = _ApiClient2.default.convertToType(data['isRequired'], 'Boolean');
                }
                if (data.hasOwnProperty('useAsFolderName')) {
                    obj['useAsFolderName'] = _ApiClient2.default.convertToType(data['useAsFolderName'], 'Boolean');
                }
                if (data.hasOwnProperty('senderEmail')) {
                    obj['senderEmail'] = _ApiClient2.default.convertToType(data['senderEmail'], 'Boolean');
                }
            }
            return obj;
        }

        /**
        * Secondary description of field.
        * @member {String} description
        */

        /**
        * How much of the available width the field should occupy
        * @member {Number} width
        */

        /**
        * Whether this field must be completed before form can be submitted
        * @member {Boolean} isRequired
        */

        /**
        * Whether to place submitted files into a subfolder named the contents of this field. Only takes effect when the `fileDropCreateFolders` parameter on the receive folder is `true`. `isRequired` must be set to `true` if this setting is `true`.
        * @member {Boolean} useAsFolderName
        */

        /**
        * @member {Boolean} senderEmail
        */

    }]);

    return FormFieldSettings;
}();

exports.default = FormFieldSettings;