'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * ExaVault API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * See our API reference documentation at https://www.exavault.com/developer/api-docs/
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 2.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Contact: support@exavault.com
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _NotificationRelationshipsOwnerUser = require('./NotificationRelationshipsOwnerUser');

var _NotificationRelationshipsOwnerUser2 = _interopRequireDefault(_NotificationRelationshipsOwnerUser);

var _NotificationRelationshipsResource = require('./NotificationRelationshipsResource');

var _NotificationRelationshipsResource2 = _interopRequireDefault(_NotificationRelationshipsResource);

var _NotificationRelationshipsShare = require('./NotificationRelationshipsShare');

var _NotificationRelationshipsShare2 = _interopRequireDefault(_NotificationRelationshipsShare);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The NotificationRelationships model module.
* @module model/NotificationRelationships
* @version 2.2.5
*/
var NotificationRelationships = function () {
    /**
    * Constructs a new <code>NotificationRelationships</code>.
    * @alias module:model/NotificationRelationships
    * @class
    */

    function NotificationRelationships() {
        _classCallCheck(this, NotificationRelationships);

        this['resource'] = undefined;
        this['share'] = undefined;
        this['ownerUser'] = undefined;
    }

    /**
    * Constructs a <code>NotificationRelationships</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NotificationRelationships} obj Optional instance to populate.
    * @return {module:model/NotificationRelationships} The populated <code>NotificationRelationships</code> instance.
    */


    _createClass(NotificationRelationships, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new NotificationRelationships();

                if (data.hasOwnProperty('resource')) {
                    obj['resource'] = _NotificationRelationshipsResource2.default.constructFromObject(data['resource']);
                }
                if (data.hasOwnProperty('share')) {
                    obj['share'] = _NotificationRelationshipsShare2.default.constructFromObject(data['share']);
                }
                if (data.hasOwnProperty('ownerUser')) {
                    obj['ownerUser'] = _NotificationRelationshipsOwnerUser2.default.constructFromObject(data['ownerUser']);
                }
            }
            return obj;
        }

        /**
        * @member {module:model/NotificationRelationshipsResource} resource
        */

        /**
        * @member {module:model/NotificationRelationshipsShare} share
        */

        /**
        * @member {module:model/NotificationRelationshipsOwnerUser} ownerUser
        */

    }]);

    return NotificationRelationships;
}();

exports.default = NotificationRelationships;