'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * ExaVault API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * See our API reference documentation at https://www.exavault.com/developer/api-docs/
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 2.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Contact: support@exavault.com
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The PlanDetailsWebhookOptions model module.
* @module model/PlanDetailsWebhookOptions
* @version 2.2.5
*/
var PlanDetailsWebhookOptions = function () {
    /**
    * Constructs a new <code>PlanDetailsWebhookOptions</code>.
    * @alias module:model/PlanDetailsWebhookOptions
    * @class
    */

    function PlanDetailsWebhookOptions() {
        _classCallCheck(this, PlanDetailsWebhookOptions);

        this['restrictionTypes'] = undefined;
        this['amount'] = undefined;
        this['includeTriggers'] = undefined;
    }

    /**
    * Constructs a <code>PlanDetailsWebhookOptions</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PlanDetailsWebhookOptions} obj Optional instance to populate.
    * @return {module:model/PlanDetailsWebhookOptions} The populated <code>PlanDetailsWebhookOptions</code> instance.
    */


    _createClass(PlanDetailsWebhookOptions, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new PlanDetailsWebhookOptions();

                if (data.hasOwnProperty('restrictionTypes')) {
                    obj['restrictionTypes'] = _ApiClient2.default.convertToType(data['restrictionTypes'], ['String']);
                }
                if (data.hasOwnProperty('amount')) {
                    obj['amount'] = _ApiClient2.default.convertToType(data['amount'], 'Number');
                }
                if (data.hasOwnProperty('includeTriggers')) {
                    obj['includeTriggers'] = _ApiClient2.default.convertToType(data['includeTriggers'], 'String');
                }
            }
            return obj;
        }

        /**
        * @member {Array.<String>} restrictionTypes
        */

        /**
        * @member {Number} amount
        */

        /**
        * @member {String} includeTriggers
        */

    }]);

    return PlanDetailsWebhookOptions;
}();

exports.default = PlanDetailsWebhookOptions;