'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * ExaVault API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * See our API reference documentation at https://www.exavault.com/developer/api-docs/
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 2.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Contact: support@exavault.com
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _AccountAllowedIpRanges = require('./AccountAllowedIpRanges');

var _AccountAllowedIpRanges2 = _interopRequireDefault(_AccountAllowedIpRanges);

var _BrandingSettingsValues = require('./BrandingSettingsValues');

var _BrandingSettingsValues2 = _interopRequireDefault(_BrandingSettingsValues);

var _CallbackSettingsValues = require('./CallbackSettingsValues');

var _CallbackSettingsValues2 = _interopRequireDefault(_CallbackSettingsValues);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The UpdateAccountRequestBody model module.
* @module model/UpdateAccountRequestBody
* @version 2.2.2
*/
var UpdateAccountRequestBody = function () {
    /**
    * Constructs a new <code>UpdateAccountRequestBody</code>.
    * @alias module:model/UpdateAccountRequestBody
    * @class
    */

    function UpdateAccountRequestBody() {
        _classCallCheck(this, UpdateAccountRequestBody);

        this['quotaNoticeEnabled'] = undefined;
        this['quotaNoticeThreshold'] = undefined;
        this['secureOnly'] = undefined;
        this['complexPasswords'] = undefined;
        this['showReferralLinks'] = undefined;
        this['externalDomain'] = undefined;
        this['emailContent'] = undefined;
        this['emailSubject'] = undefined;
        this['allowedIpRanges'] = undefined;
        this['callbackSettings'] = undefined;
        this['brandingSettings'] = undefined;
        this['accountOnboarding'] = undefined;
        this['customSignature'] = undefined;
    }

    /**
    * Constructs a <code>UpdateAccountRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UpdateAccountRequestBody} obj Optional instance to populate.
    * @return {module:model/UpdateAccountRequestBody} The populated <code>UpdateAccountRequestBody</code> instance.
    */


    _createClass(UpdateAccountRequestBody, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new UpdateAccountRequestBody();

                if (data.hasOwnProperty('quotaNoticeEnabled')) {
                    obj['quotaNoticeEnabled'] = _ApiClient2.default.convertToType(data['quotaNoticeEnabled'], 'Boolean');
                }
                if (data.hasOwnProperty('quotaNoticeThreshold')) {
                    obj['quotaNoticeThreshold'] = _ApiClient2.default.convertToType(data['quotaNoticeThreshold'], 'Number');
                }
                if (data.hasOwnProperty('secureOnly')) {
                    obj['secureOnly'] = _ApiClient2.default.convertToType(data['secureOnly'], 'Boolean');
                }
                if (data.hasOwnProperty('complexPasswords')) {
                    obj['complexPasswords'] = _ApiClient2.default.convertToType(data['complexPasswords'], 'Boolean');
                }
                if (data.hasOwnProperty('showReferralLinks')) {
                    obj['showReferralLinks'] = _ApiClient2.default.convertToType(data['showReferralLinks'], 'Boolean');
                }
                if (data.hasOwnProperty('externalDomain')) {
                    obj['externalDomain'] = _ApiClient2.default.convertToType(data['externalDomain'], 'String');
                }
                if (data.hasOwnProperty('emailContent')) {
                    obj['emailContent'] = _ApiClient2.default.convertToType(data['emailContent'], 'String');
                }
                if (data.hasOwnProperty('emailSubject')) {
                    obj['emailSubject'] = _ApiClient2.default.convertToType(data['emailSubject'], 'String');
                }
                if (data.hasOwnProperty('allowedIpRanges')) {
                    obj['allowedIpRanges'] = _ApiClient2.default.convertToType(data['allowedIpRanges'], [_AccountAllowedIpRanges2.default]);
                }
                if (data.hasOwnProperty('callbackSettings')) {
                    obj['callbackSettings'] = _CallbackSettingsValues2.default.constructFromObject(data['callbackSettings']);
                }
                if (data.hasOwnProperty('brandingSettings')) {
                    obj['brandingSettings'] = _BrandingSettingsValues2.default.constructFromObject(data['brandingSettings']);
                }
                if (data.hasOwnProperty('accountOnboarding')) {
                    obj['accountOnboarding'] = _ApiClient2.default.convertToType(data['accountOnboarding'], 'Boolean');
                }
                if (data.hasOwnProperty('customSignature')) {
                    obj['customSignature'] = _ApiClient2.default.convertToType(data['customSignature'], 'String');
                }
            }
            return obj;
        }

        /**
        * Whether the system should email the account owner when usage exceeds quotaNoticeThreshold value
        * @member {Boolean} quotaNoticeEnabled
        */

        /**
        * Percent of account usage to trigger quota notices for.
        * @member {Number} quotaNoticeThreshold
        */

        /**
        * Whether unencrypted FTP connections should be denied for the account.
        * @member {Boolean} secureOnly
        */

        /**
        * Whether to require complex passwords for all passwords.
        * @member {Boolean} complexPasswords
        */

        /**
        * Whether to display links for others to sign up on share views and invitation emails
        * @member {Boolean} showReferralLinks
        */

        /**
        * Custom address used for web file manager. Not available for all account types.
        * @member {String} externalDomain
        */

        /**
        * Content of welcome email template.
        * @member {String} emailContent
        */

        /**
        * Subject line for welcome emails
        * @member {String} emailSubject
        */

        /**
        * IP Address Ranges for restricting account access
        * @member {Array.<module:model/AccountAllowedIpRanges>} allowedIpRanges
        */

        /**
        * @member {module:model/CallbackSettingsValues} callbackSettings
        */

        /**
        * @member {module:model/BrandingSettingsValues} brandingSettings
        */

        /**
        * Whether extra help popups can be enabled for users in the web file manager.
        * @member {Boolean} accountOnboarding
        */

        /**
        * Signature to be automatically added to the bottom of emails generated by the account.
        * @member {String} customSignature
        */

    }]);

    return UpdateAccountRequestBody;
}();

exports.default = UpdateAccountRequestBody;