'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * ExaVault API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * See our API reference documentation at https://www.exavault.com/developer/api-docs/
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 2.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Contact: support@exavault.com
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _WebhookV1Details = require('./WebhookV1Details');

var _WebhookV1Details2 = _interopRequireDefault(_WebhookV1Details);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The WebhookActivityAttributesV1 model module.
* @module model/WebhookActivityAttributesV1
* @version 2.2.5
*/
var WebhookActivityAttributesV1 = function () {
    /**
    * Constructs a new <code>WebhookActivityAttributesV1</code>.
    * @alias module:model/WebhookActivityAttributesV1
    * @class
    */

    function WebhookActivityAttributesV1() {
        _classCallCheck(this, WebhookActivityAttributesV1);

        this['webhookId'] = undefined;
        this['webhookFormat'] = undefined;
        this['attemptId'] = undefined;
        this['accountId'] = undefined;
        this['resend'] = undefined;
        this['endpointUrl'] = undefined;
        this['event'] = undefined;
        this['status'] = undefined;
        this['ipAddress'] = undefined;
        this['response'] = undefined;
        this['details'] = undefined;
        this['webhookPath'] = undefined;
        this['resourcePath'] = undefined;
        this['username'] = undefined;
        this['created'] = undefined;
    }

    /**
    * Constructs a <code>WebhookActivityAttributesV1</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WebhookActivityAttributesV1} obj Optional instance to populate.
    * @return {module:model/WebhookActivityAttributesV1} The populated <code>WebhookActivityAttributesV1</code> instance.
    */


    _createClass(WebhookActivityAttributesV1, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new WebhookActivityAttributesV1();

                if (data.hasOwnProperty('webhookId')) {
                    obj['webhookId'] = _ApiClient2.default.convertToType(data['webhookId'], 'Number');
                }
                if (data.hasOwnProperty('webhookFormat')) {
                    obj['webhookFormat'] = _ApiClient2.default.convertToType(data['webhookFormat'], 'String');
                }
                if (data.hasOwnProperty('attemptId')) {
                    obj['attemptId'] = _ApiClient2.default.convertToType(data['attemptId'], 'String');
                }
                if (data.hasOwnProperty('accountId')) {
                    obj['accountId'] = _ApiClient2.default.convertToType(data['accountId'], 'String');
                }
                if (data.hasOwnProperty('resend')) {
                    obj['resend'] = _ApiClient2.default.convertToType(data['resend'], 'Boolean');
                }
                if (data.hasOwnProperty('endpointUrl')) {
                    obj['endpointUrl'] = _ApiClient2.default.convertToType(data['endpointUrl'], 'String');
                }
                if (data.hasOwnProperty('event')) {
                    obj['event'] = _ApiClient2.default.convertToType(data['event'], 'String');
                }
                if (data.hasOwnProperty('status')) {
                    obj['status'] = _ApiClient2.default.convertToType(data['status'], 'Number');
                }
                if (data.hasOwnProperty('ipAddress')) {
                    obj['ipAddress'] = _ApiClient2.default.convertToType(data['ipAddress'], 'String');
                }
                if (data.hasOwnProperty('response')) {
                    obj['response'] = _ApiClient2.default.convertToType(data['response'], 'String');
                }
                if (data.hasOwnProperty('details')) {
                    obj['details'] = _WebhookV1Details2.default.constructFromObject(data['details']);
                }
                if (data.hasOwnProperty('webhookPath')) {
                    obj['webhookPath'] = _ApiClient2.default.convertToType(data['webhookPath'], 'String');
                }
                if (data.hasOwnProperty('resourcePath')) {
                    obj['resourcePath'] = _ApiClient2.default.convertToType(data['resourcePath'], 'String');
                }
                if (data.hasOwnProperty('username')) {
                    obj['username'] = _ApiClient2.default.convertToType(data['username'], 'String');
                }
                if (data.hasOwnProperty('created')) {
                    obj['created'] = _ApiClient2.default.convertToType(data['created'], 'String');
                }
            }
            return obj;
        }

        /**
        * Unique ID of webhook configuration
        * @member {Number} webhookId
        */

        /**
        * What version of webhook message is being sent `v1`
        * @member {String} webhookFormat
        */

        /**
        * Event - retry identifier
        * @member {String} attemptId
        */

        /**
        * Unique ID of account
        * @member {String} accountId
        */

        /**
        * Whether this attempt was a re-send of a previous attempt
        * @member {Boolean} resend
        */

        /**
        * The URL the message was sent to
        * @member {String} endpointUrl
        */

        /**
        * Event type
        * @member {module:model/WebhookActivityAttributesV1.EventEnum} event
        */

        /**
        * HTTP Status Code returned by webhook listener
        * @member {Number} status
        */

        /**
        * IP Address of related activity
        * @member {String} ipAddress
        */

        /**
        * Body of web response returned by webhook listener
        * @member {String} response
        */

        /**
        * @member {module:model/WebhookV1Details} details
        */

        /**
        * Path that webhook is watching
        * @member {String} webhookPath
        */

        /**
        * Path of resource that matched webhook
        * @member {String} resourcePath
        */

        /**
        * Username of related activity
        * @member {String} username
        */

        /**
        * Date and time of webhook message being generated by system
        * @member {String} created
        */


        /**
        * Allowed values for the <code>event</code> property.
        * @enum {String}
        * @readonly
        */

    }]);

    return WebhookActivityAttributesV1;
}();

WebhookActivityAttributesV1.EventEnum = {
    /**
     * value: "resources.upload"
     * @const
     */
    "resources.upload": "resources.upload",
    /**
     * value: "resources.download"
     * @const
     */
    "resources.download": "resources.download",
    /**
     * value: "resources.delete"
     * @const
     */
    "resources.delete": "resources.delete",
    /**
     * value: "resources.rename"
     * @const
     */
    "resources.rename": "resources.rename",
    /**
     * value: "resources.copy"
     * @const
     */
    "resources.copy": "resources.copy",
    /**
     * value: "resources.move"
     * @const
     */
    "resources.move": "resources.move",
    /**
     * value: "resources.compress"
     * @const
     */
    "resources.compress": "resources.compress",
    /**
     * value: "resources.extract"
     * @const
     */
    "resources.extract": "resources.extract",
    /**
     * value: "resources.createFolder"
     * @const
     */
    "resources.createFolder": "resources.createFolder",
    /**
     * value: "shares.formSubmit"
     * @const
     */
    "shares.formSubmit": "shares.formSubmit" };
exports.default = WebhookActivityAttributesV1;