'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * ExaVault API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * See our API reference documentation at https://www.exavault.com/developer/api-docs/
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 2.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Contact: support@exavault.com
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The WebhookV2EventDataResources model module.
* @module model/WebhookV2EventDataResources
* @version 2.2.4
*/
var WebhookV2EventDataResources = function () {
    /**
    * Constructs a new <code>WebhookV2EventDataResources</code>.
    * @alias module:model/WebhookV2EventDataResources
    * @class
    */

    function WebhookV2EventDataResources() {
        _classCallCheck(this, WebhookV2EventDataResources);

        this['id'] = undefined;
        this['hash'] = undefined;
        this['name'] = undefined;
        this['type'] = undefined;
        this['createdBy'] = undefined;
        this['uploadDate'] = undefined;
        this['createdAt'] = undefined;
        this['updatedAt'] = undefined;
        this['accessedAt'] = undefined;
        this['path'] = undefined;
        this['size'] = undefined;
        this['fileCount'] = undefined;
        this['previewable'] = undefined;
    }

    /**
    * Constructs a <code>WebhookV2EventDataResources</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WebhookV2EventDataResources} obj Optional instance to populate.
    * @return {module:model/WebhookV2EventDataResources} The populated <code>WebhookV2EventDataResources</code> instance.
    */


    _createClass(WebhookV2EventDataResources, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new WebhookV2EventDataResources();

                if (data.hasOwnProperty('id')) {
                    obj['id'] = _ApiClient2.default.convertToType(data['id'], 'Number');
                }
                if (data.hasOwnProperty('hash')) {
                    obj['hash'] = _ApiClient2.default.convertToType(data['hash'], 'String');
                }
                if (data.hasOwnProperty('name')) {
                    obj['name'] = _ApiClient2.default.convertToType(data['name'], 'String');
                }
                if (data.hasOwnProperty('type')) {
                    obj['type'] = _ApiClient2.default.convertToType(data['type'], 'String');
                }
                if (data.hasOwnProperty('createdBy')) {
                    obj['createdBy'] = _ApiClient2.default.convertToType(data['createdBy'], 'String');
                }
                if (data.hasOwnProperty('uploadDate')) {
                    obj['uploadDate'] = _ApiClient2.default.convertToType(data['uploadDate'], 'Date');
                }
                if (data.hasOwnProperty('createdAt')) {
                    obj['createdAt'] = _ApiClient2.default.convertToType(data['createdAt'], 'Date');
                }
                if (data.hasOwnProperty('updatedAt')) {
                    obj['updatedAt'] = _ApiClient2.default.convertToType(data['updatedAt'], 'Date');
                }
                if (data.hasOwnProperty('accessedAt')) {
                    obj['accessedAt'] = _ApiClient2.default.convertToType(data['accessedAt'], 'Date');
                }
                if (data.hasOwnProperty('path')) {
                    obj['path'] = _ApiClient2.default.convertToType(data['path'], 'String');
                }
                if (data.hasOwnProperty('size')) {
                    obj['size'] = _ApiClient2.default.convertToType(data['size'], 'Number');
                }
                if (data.hasOwnProperty('fileCount')) {
                    obj['fileCount'] = _ApiClient2.default.convertToType(data['fileCount'], 'Number');
                }
                if (data.hasOwnProperty('previewable')) {
                    obj['previewable'] = _ApiClient2.default.convertToType(data['previewable'], 'Boolean');
                }
            }
            return obj;
        }

        /**
        * Resource ID
        * @member {Number} id
        */

        /**
        * Resource hash value
        * @member {String} hash
        */

        /**
        * Resource name
        * @member {String} name
        */

        /**
        * Type of resource `file` or `dir`
        * @member {String} type
        */

        /**
        * Username who originally created resource
        * @member {String} createdBy
        */

        /**
        * Date resource was first uploaded
        * @member {Date} uploadDate
        */

        /**
        * Date and time of resource creation
        * @member {Date} createdAt
        */

        /**
        * Date and time resource was most recently changed
        * @member {Date} updatedAt
        */

        /**
        * Date and time resource was most recently downloaded
        * @member {Date} accessedAt
        */

        /**
        * Full path to resource
        * @member {String} path
        */

        /**
        * Size of resource in bytes
        * @member {Number} size
        */

        /**
        * Number of resources contained in this folder. If this is a file, fileCount is null
        * @member {Number} fileCount
        */

        /**
        * Whether the resource can be previewed
        * @member {Boolean} previewable
        */

    }]);

    return WebhookV2EventDataResources;
}();

exports.default = WebhookV2EventDataResources;