'use strict';

var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; };

/**
 * ExaVault API
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if ((typeof module === 'undefined' ? 'undefined' : _typeof(module)) === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ExaVaultApi);
  }
})(undefined, function (expect, ExaVaultApi) {
  'use strict';

  var instance;

  beforeEach(function () {
    instance = new ExaVaultApi.CallbackSettingsTriggers();
  });

  var getProperty = function getProperty(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function') return object[getter]();else return object[property];
  };

  var setProperty = function setProperty(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function') object[setter](value);else object[property] = value;
  };

  describe('CallbackSettingsTriggers', function () {
    it('should create an instance of CallbackSettingsTriggers', function () {
      // uncomment below and update the code to test CallbackSettingsTriggers
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be.a(ExaVaultApi.CallbackSettingsTriggers);
    });

    it('should have the property upload (base name: "upload")', function () {
      // uncomment below and update the code to test the property upload
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property download (base name: "download")', function () {
      // uncomment below and update the code to test the property download
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property _delete (base name: "delete")', function () {
      // uncomment below and update the code to test the property _delete
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property createFolder (base name: "createFolder")', function () {
      // uncomment below and update the code to test the property createFolder
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property rename (base name: "rename")', function () {
      // uncomment below and update the code to test the property rename
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property move (base name: "move")', function () {
      // uncomment below and update the code to test the property move
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property copy (base name: "copy")', function () {
      // uncomment below and update the code to test the property copy
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property compress (base name: "compress")', function () {
      // uncomment below and update the code to test the property compress
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property extract (base name: "extract")', function () {
      // uncomment below and update the code to test the property extract
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property shareFolder (base name: "shareFolder")', function () {
      // uncomment below and update the code to test the property shareFolder
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property sendFiles (base name: "sendFiles")', function () {
      // uncomment below and update the code to test the property sendFiles
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property receiveFiles (base name: "receiveFiles")', function () {
      // uncomment below and update the code to test the property receiveFiles
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property updateShare (base name: "updateShare")', function () {
      // uncomment below and update the code to test the property updateShare
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property updateReceive (base name: "updateReceive")', function () {
      // uncomment below and update the code to test the property updateReceive
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property deleteSend (base name: "deleteSend")', function () {
      // uncomment below and update the code to test the property deleteSend
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property deleteReceive (base name: "deleteReceive")', function () {
      // uncomment below and update the code to test the property deleteReceive
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property deleteShare (base name: "deleteShare")', function () {
      // uncomment below and update the code to test the property deleteShare
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property createNotification (base name: "createNotification")', function () {
      // uncomment below and update the code to test the property createNotification
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property updateNotification (base name: "updateNotification")', function () {
      // uncomment below and update the code to test the property updateNotification
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property deleteNotification (base name: "deleteNotification")', function () {
      // uncomment below and update the code to test the property deleteNotification
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property createUser (base name: "createUser")', function () {
      // uncomment below and update the code to test the property createUser
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property updateUser (base name: "updateUser")', function () {
      // uncomment below and update the code to test the property updateUser
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property deleteUser (base name: "deleteUser")', function () {
      // uncomment below and update the code to test the property deleteUser
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property userConnect (base name: "userConnect")', function () {
      // uncomment below and update the code to test the property userConnect
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });

    it('should have the property userDisconnect (base name: "userDisconnect")', function () {
      // uncomment below and update the code to test the property userDisconnect
      //var instane = new ExaVaultApi.CallbackSettingsTriggers();
      //expect(instance).to.be();
    });
  });
});