'use strict';

var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; };

/**
 * ExaVault API
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if ((typeof module === 'undefined' ? 'undefined' : _typeof(module)) === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ExaVaultApi);
  }
})(undefined, function (expect, ExaVaultApi) {
  'use strict';

  var instance;

  beforeEach(function () {
    instance = new ExaVaultApi.UserPermissions();
  });

  var getProperty = function getProperty(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function') return object[getter]();else return object[property];
  };

  var setProperty = function setProperty(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function') object[setter](value);else object[property] = value;
  };

  describe('UserPermissions', function () {
    it('should create an instance of UserPermissions', function () {
      // uncomment below and update the code to test UserPermissions
      //var instane = new ExaVaultApi.UserPermissions();
      //expect(instance).to.be.a(ExaVaultApi.UserPermissions);
    });

    it('should have the property download (base name: "download")', function () {
      // uncomment below and update the code to test the property download
      //var instane = new ExaVaultApi.UserPermissions();
      //expect(instance).to.be();
    });

    it('should have the property upload (base name: "upload")', function () {
      // uncomment below and update the code to test the property upload
      //var instane = new ExaVaultApi.UserPermissions();
      //expect(instance).to.be();
    });

    it('should have the property modify (base name: "modify")', function () {
      // uncomment below and update the code to test the property modify
      //var instane = new ExaVaultApi.UserPermissions();
      //expect(instance).to.be();
    });

    it('should have the property _delete (base name: "delete")', function () {
      // uncomment below and update the code to test the property _delete
      //var instane = new ExaVaultApi.UserPermissions();
      //expect(instance).to.be();
    });

    it('should have the property list (base name: "list")', function () {
      // uncomment below and update the code to test the property list
      //var instane = new ExaVaultApi.UserPermissions();
      //expect(instance).to.be();
    });

    it('should have the property changePassword (base name: "changePassword")', function () {
      // uncomment below and update the code to test the property changePassword
      //var instane = new ExaVaultApi.UserPermissions();
      //expect(instance).to.be();
    });

    it('should have the property share (base name: "share")', function () {
      // uncomment below and update the code to test the property share
      //var instane = new ExaVaultApi.UserPermissions();
      //expect(instance).to.be();
    });

    it('should have the property notification (base name: "notification")', function () {
      // uncomment below and update the code to test the property notification
      //var instane = new ExaVaultApi.UserPermissions();
      //expect(instance).to.be();
    });

    it('should have the property viewFormData (base name: "viewFormData")', function () {
      // uncomment below and update the code to test the property viewFormData
      //var instane = new ExaVaultApi.UserPermissions();
      //expect(instance).to.be();
    });

    it('should have the property deleteFormData (base name: "deleteFormData")', function () {
      // uncomment below and update the code to test the property deleteFormData
      //var instane = new ExaVaultApi.UserPermissions();
      //expect(instance).to.be();
    });
  });
});